#trainer: energy
trainer: pykaleenergy
logger: tensorboard

task:
  dataset: lmdb
  description: "Regressing the energies"
  type: regression
  metric: mae



dataset:
  train:
    src: data/data/omdb/band_gap/random_train/
  val:
    src: data/data/omdb/band_gap/random_valid/
  test:
    src: data/data/omdb/band_gap/random_test/


model:
 name: leftnet
 cutoff: 6.0
 hidden_channels: 128
 num_layers: 4
 num_radial: 32
 regress_forces: False
 use_pbc: True
 otf_graph: False
 output_dim: 1

optim:
 batch_size: 1
 eval_batch_size: 1
 num_workers: 0
 lr_initial: 0.0005
 lr_gamma: 0.1
 lr_milestones:
  - 5000000000
 warmup_steps: -1
 warmup_factor: 1.0
 max_epochs: 10
# max_epochs: 500
 eval_every: 500
